Upsell notification
Codeinwp/templates-patterns-collection pull request #130
Opened 2021-12-16 22:26 UTC by UVLabs

### Summary
Adds upsell notification to all builder tabs except Elementor builder tab

### Test instructions

- The upsell notice should  whether a user is not using a valid license
- The notice should show in all tabs except elementor

Closes Codeinwp/neve-pro-addon#1739

2021-12-17 08:12 UTC, abaicus requested changes
Thanks, @UVLabs! 👍🏻 For the most part, it looks good, except what I mentioned in the review comments. 

@cristian-ungureanu I'm not sure if we should add an external link icon to the button.

2021-12-17 08:12 UTC, abaicus commented on assets/src/scss/_media-queries.scss
> +@media( max-width: #{$tablet}){
@UVLabs The CSS for this is mobile-first and only uses min-width media queries. Let's respect the convention and to the styles like that 👍🏻

2021-12-17 08:12 UTC, abaicus commented on assets/src/Components/StarterSites/Filters.js
> +					}
Please enable eslint formatting on save on your end or run `eslint --fix` on this file 🦭

2021-12-17 09:29 UTC, cristian-ungureanu commented
@UVLabs Andrei is right, the buttons should not have the external link icon.

2021-12-17 09:30 UTC, abaicus commented
@cristian-ungureanu I was saying that it doesn't have, but it goes to an external link, so I think maybe we should be adding one 👀

2021-12-17 09:44 UTC, cristian-ungureanu commented
@abaicus I was looking at other buttons in the dashboard that are leading to an external link and took the example from there: https://vertis.d.pr/qXWv5q, https://vertis.d.pr/RgPvj9, https://vertis.d.pr/35ZLmZ ... in this case, we should update other buttons too.

2021-12-17 09:45 UTC, abaicus commented
Ok, makes sense. 👍🏻

2021-12-17 09:55 UTC, cristian-ungureanu commented
@UVLabs let's add the external icon in the button too and I will create another task to update the others. 
Also, let's add this notice in Elementor's tab too.

2021-12-20 19:27 UTC, UVLabs commented
@cristian-ungureanu @abaicus I've made the changes here

2021-12-23 10:50 UTC, cristian-ungureanu commented
@UVLabs can you have a look and fix the changes here?

2021-12-23 13:52 UTC, merged

2021-12-23 16:18 UTC, ineagu commented
@cristian-ungureanu The original description was that the notice would be shown only for tabs where there are exclusively pro sites: https://github.com/Codeinwp/neve-pro-addon/issues/1739, however I see it as well on the gutenberg tab. Which is not ideal, especially at the first view.