Have TPC Neve independent
Codeinwp/templates-patterns-collection pull request #155
Opened 2022-07-19 13:05 UTC by preda-bogdan

### Summary

- [x] Remove the Notice that Neve is required from Plugins
- [x] I will remove the pop-up when Neve is not present on Starter Sites and add Neve as part of the required Install.
- [ ] For Page Templates I will let them import the template without requiring them to have Neve.
- [ ] I will ensure that if the Neve Pro license is available, the Template Cloud is available even if the Neve theme is not being used. My Library should be available on other themes if the License is active.

### Test instructions

- 
- 

Closes #154.

2022-07-21 09:57 UTC, ineagu commented
As I remember page templates aren't working great without Neve. so I am thinking that while we can leave those things there, if a user doesn't have Neve installed, I would hide starter sites, page templates & so on and focus on My templates part, with a nice onboarding screen/exp.

So I would look at the project as 2 sub-projects: 1. Pre-made templates and 2. Cloud Library.

2022-07-21 10:29 UTC, preda-bogdan commented
Right now with the changes from here if the starter site or parts of the starter site will be imported, we will install and activate Neve for those. For the Page Templates, we do not require that. However, I agree that those should display correctly. I think the next step would be to review the Page Templates and make sure that they work independently of the installed theme.

The end goal is to allow the usage of Pre-made templates and Cloud Library without requiring the presence of Neve from my understanding. But I think it will happen in a couple of steps.

2022-07-28 06:14 UTC, cristian-ungureanu requested changes
Everything looks good @preda-bogdan, just one small change is required. You did a wonderful job 🚀

2022-07-28 06:14 UTC, cristian-ungureanu commented on assets/src/Components/CloudLibrary/Library.js
> +					`<a href="${ themeURL }" target="_blank" rel="noreferrer">${ __(
We should not translate theme and plugin name so no need to add __ before "Neve" and "Neve Pro Addon"

2022-07-28 08:49 UTC, cristian-ungureanu approved these changes

2022-07-28 08:50 UTC, merged