Release
Codeinwp/templates-patterns-collection pull request #229
Opened 2023-03-08 09:09 UTC by preda-bogdan

- Updated dependencies

2023-03-16 17:48 UTC, selul requested changes

2023-03-16 17:48 UTC, selul commented on includes/Admin.php
> +use function Sodium\add;
This is a typo here, no?

2023-03-16 17:57 UTC, preda-bogdan commented on includes/Admin.php
> +use function Sodium\add;
Yes, for sure. Thank you!

2023-03-17 09:28 UTC, selul approved these changes

2023-03-17 09:33 UTC, merged